[package]
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
description = "Analiticcl is an approximate string matching or fuzzy-matching system that can be used to find variants for spelling correction or text normalisation"
edition = "2018"
name = "analiticcl"
version = "0.1.0"
homepage = "https://github.com/proycon/analiticcl"
repository = "https://github.com/proycon/analiticcl"
documentation = "https://docs.rs/analiticcl"
keywords = ["nlp","text-processing","spelling correction","linguistics","spellcheck"]
license = "GPL-3.0+"
readme = "README.md"

[[bench]]
harness = false
name = "benchmarks"

[dependencies]
clap = "*"
num-bigint = "*"
num-traits = "*"
rayon = "*"
sesdiff = "*"

[dev-dependencies]
criterion = "*"
