[package]
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
description = "Analiticcl is an approximate string matching or fuzzy-matching system that can be used to find variants for spelling correction or text normalisation"
documentation = "https://docs.rs/analiticcl"
edition = "2018"
homepage = "https://github.com/proycon/analiticcl"
keywords = ["nlp", "text-processing", "spelling-correction", "linguistics", "spellcheck"]
license = "GPL-3.0+"
name = "analiticcl"
readme = "README.md"
repository = "https://github.com/proycon/analiticcl"
version = "0.3.0"
[[bench]]
harness = false
name = "benchmarks"

[dependencies]
clap = "2.33.0"
ibig = "0.3.2"
num-traits = "0.2.14"
rayon = "1.5.0"
rustfst = "*"
sesdiff = "0.3.0"

[dev-dependencies]
criterion = "0.3.4"
