name: Rust CI

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'bindings/**'

  pull_request:
    branches: [master]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify start to ##gitlama
    steps:
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: |-
            ${{ github.actor }} started a build of Analiticcl

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install cargo rustc python3 python3-pip
                cd bindings/python
                python -m venv .env
                source .env/bin/activate
                pip install setuptools_rust
                pip install -r requirements.txt
                pip install .
             fi

      - name: Build and test
        id: test
        run: cargo test
        continue-on-error: true

      - name: Install Python Test Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                cd bindings/python
                python -m venv .env
                source .env/bin/activate
                pip install setuptools_rust
                pip install -r requirements.txt
                pip install .
             fi

      - name: Test Python binding
        id: test_python_binding
        run: cd bindings/python && python -m venv .env && source .env/bin/activate && python tests/tests.py
        continue-on-error: true

      - name: Notify IRC of failure
        if: ${{ steps.test.outcome != 'success' || steps.test_python_binding.outcome != 'success' }}
        uses: Gottox/irc-message-action@v1
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: |-
            Building and testing analiticcl by ${{ github.actor }} on ${{ runner.os }}: FAILED

      - name: Notify IRC of success
        if: ${{ steps.test.outcome == 'success' && steps.test_python_binding.outcome == 'success'}}
        uses: Gottox/irc-message-action@v1
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: |-
            Building and testing analiticcl by ${{ github.actor }} on ${{ runner.os }}: SUCCESS
